sudo: required
services:
  - docker

before_install:
  - docker build -t andreygorelov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andreygorelov/docker-react npm run test

deploy:
  provider: "elasticbeanstalk"
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-485577343072"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_ACCESS_SECRET"